title: yuzhi
subtitle: ''
description: ''
keywords:
author: yuzhi
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.yefeng.love
permalink: :year/:month/:day/:title/
#root: /hexo/
theme: "Chic"
auto_category:
 enable: true
 multiple: false
 depth: 2
deploy:
 type: git
 repo: https://github.com/yuzhi-jiang/hexo
 # example, https://github.com/hexojs/hexojs.github.io
 branch: gh-pages